#This file is to standardise every student's openclaw to 2026.4.24 for workshop purposes.


services:
  openclaw:
    image: ghcr.io/openclaw/openclaw:2026.4.24
    init: true
    ports:
      - "18789:18789"
    environment:
      - OPENCLAW_GATEWAY_BIND=lan
    restart: unless-stopped
    volumes:
      - ./data:/home/node/.openclaw
      - ./data/workspace:/home/node/.openclaw/workspace
